In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
df = pd.read_csv("../data/taxi_trip_pricing.csv")

df.head()

   Trip_Distance_km Time_of_Day  ... Trip_Duration_Minutes  Trip_Price
0             19.35     Morning  ...                 53.82     36.2624
1             47.59   Afternoon  ...                 40.57         NaN
2             36.87     Evening  ...                 37.27     52.9032
3             30.33     Evening  ...                116.81     36.4698
4               NaN     Evening  ...                 22.64     15.6180

[5 rows x 11 columns]

In [3]:
df = df.dropna(subset=["Trip_Price"])

In [5]:
df["Trip_Price"].isnull().sum()

np.int64(0)

In [6]:
X = df.drop(columns=["Trip_Price"])
y = df["Trip_Price"]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [8]:
X_train.shape

(760, 10)

In [9]:
X_test.shape

(191, 10)

In [16]:
# This will always predict the y_train mean
baseline_model = DummyRegressor(
    strategy="mean"
)

In [19]:
baseline_model.fit(X_train, y_train)

DummyRegressor()

In [20]:
# This constant is the mean of the y_train data
baseline_model.constant_

array([[56.03263214]])

In [21]:
print("Baseline predictions: ", baseline_model.constant_[0][0])

Baseline predictions:  56.03263214474346

In [22]:
# The dummy regressor constant or the predictions that it will give for any input is same as the mean of the y_train data
y_train.mean()

np.float64(56.03263214474346)

In [23]:
baseline_predictions = baseline_model.predict(X_test)

In [25]:
# All the predictions are same as the y_mean as it will always give the constant that is the mean of the y_train data
baseline_predictions[:10]

array([56.03263214, 56.03263214, 56.03263214, 56.03263214, 56.03263214,
       56.03263214, 56.03263214, 56.03263214, 56.03263214, 56.03263214])

In [26]:
comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": baseline_predictions
})

comparison.head()

    Actual  Predicted
0  31.3844  56.032632
1  97.4848  56.032632
2  19.1069  56.032632
3  47.1770  56.032632
4  55.7598  56.032632

In [29]:
# The baseline model has an average absolute error of 26.60 units
baseline_mae = mean_absolute_error(y_test, baseline_predictions)

print("Baseline MAE: ", baseline_mae)

Baseline MAE:  26.60884292791942

In [31]:
baseline_mse = mean_squared_error(y_test, baseline_predictions)

print("Baseline MSE:", baseline_mse)

Baseline MSE: 2354.960686332609

In [32]:
baseline_rmse = np.sqrt(baseline_mse)

print("Baseline RMSE: ", baseline_rmse)

Baseline RMSE:  48.52793717367975

In [33]:
baseline_r2 = r2_score(y_test, baseline_predictions)

print("Baseline R²: ", baseline_r2)

Baseline R²:  -0.007522028914421552

In [39]:
baseline_results = pd.DataFrame({
    "Model": ["Mean Baseline"],
    "MAE": [baseline_mae],
    "MSE": [baseline_mse],
    "RMSE": [baseline_rmse],
    "R²": [baseline_r2]
})

baseline_results

           Model        MAE          MSE       RMSE        R²
0  Mean Baseline  26.608843  2354.960686  48.527937 -0.007522

## Baseline Conclusion

A mean-based regression baseline was established using the mean
`Trip_Price` from the training set.

The baseline predicts the same price for every test observation
and does not use any input features.

The baseline metrics provide a reference point for evaluating
Simple Linear Regression and Multiple Linear Regression.

The subsequent models should improve upon this baseline by using
information contained in the input features.